# Generated by Django 6.0 on 2025-12-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standard hourly charge', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_link',
            field=models.URLField(blank=True, help_text='Link to portfolio', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='minimum_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price for a tattoo', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text="Artist's avatar or logo", null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='styles',
            field=models.CharField(blank=True, help_text='Comma-separated styles (e.g. Realism, Traditional, Dotwork)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, help_text='How long have you been tattooing?', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Short description about yourself', null=True),
        ),
    ]
